"""change orders

Revision ID: 07c1a627e46e
Revises: f4b742a5c5b9
Create Date: 2026-01-31 19:51:52.427409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c1a627e46e'
down_revision: Union[str, Sequence[str], None] = 'f4b742a5c5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inbox_messages', ['idempotency_key'])
    op.alter_column('orders', 'idempotency_key',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'inbox_messages', type_='unique')
    # ### end Alembic commands ###
