"""change orders

Revision ID: 13cde68fd102
Revises: 07c1a627e46e
Create Date: 2026-02-02 10:45:16.773329

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "13cde68fd102"
down_revision: Union[str, Sequence[str], None] = "07c1a627e46e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
