"""update order model

Revision ID: 5cd9c0eb99bc
Revises: aab4f8247d54
Create Date: 2026-01-29 08:07:51.990497

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cd9c0eb99bc"
down_revision: Union[str, Sequence[str], None] = "aab4f8247d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
