"""I

Revision ID: d9ae63693a76
Revises: 19203a8c2b9e
Create Date: 2026-01-21 23:31:21.137680

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9ae63693a76"
down_revision: Union[str, Sequence[str], None] = "19203a8c2b9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("idempotency_key", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "orders", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_column("orders", "idempotency_key")
    # ### end Alembic commands ###
