"""update order model

Revision ID: e507864adedc
Revises: d9ae63693a76
Create Date: 2026-01-24 18:39:05.364340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e507864adedc"
down_revision: Union[str, Sequence[str], None] = "d9ae63693a76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "amount")
    # ### end Alembic commands ###
