"""inbox

Revision ID: f4b742a5c5b9
Revises: b8a7cff24c89
Create Date: 2026-01-31 14:46:39.521514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4b742a5c5b9'
down_revision: Union[str, Sequence[str], None] = 'b8a7cff24c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_messages',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('ORDER_CREATED', 'ORDER_SHIPPED', 'ORDER_PAID', 'ORDER_CANCELLED', name='eventtypeenum', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', name='inboxeventstatusenum', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatusenum'),
               type_=sa.Enum('NEW', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatusenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('outbox_events', 'event_type',
               existing_type=postgresql.ENUM('ORDER_CREATED', 'ORDER_SHIPPED', 'ORDER_PAID', 'ORDER_CANCELLED', name='eventtypeenum'),
               type_=sa.Enum('ORDER_CREATED', 'ORDER_SHIPPED', 'ORDER_PAID', 'ORDER_CANCELLED', name='eventtypeenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('outbox_events', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='outboxeventstatusenum'),
               type_=sa.Enum('PENDING', 'SENT', 'FAILED', name='outboxeventstatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::outboxeventstatusenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox_events', 'status',
               existing_type=sa.Enum('PENDING', 'SENT', 'FAILED', name='outboxeventstatusenum', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='outboxeventstatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::outboxeventstatusenum"))
    op.alter_column('outbox_events', 'event_type',
               existing_type=sa.Enum('ORDER_CREATED', 'ORDER_SHIPPED', 'ORDER_PAID', 'ORDER_CANCELLED', name='eventtypeenum', native_enum=False),
               type_=postgresql.ENUM('ORDER_CREATED', 'ORDER_SHIPPED', 'ORDER_PAID', 'ORDER_CANCELLED', name='eventtypeenum'),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('NEW', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatusenum', native_enum=False),
               type_=postgresql.ENUM('NEW', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatusenum'),
               existing_nullable=False)
    op.drop_table('inbox_messages')
    # ### end Alembic commands ###
