"""update order model

Revision ID: fd1c32d769c2
Revises: e507864adedc
Create Date: 2026-01-24 18:40:13.853738

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd1c32d769c2"
down_revision: Union[str, Sequence[str], None] = "e507864adedc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###
